### ISSUE TITLE
Any other SDKs like Clang or Python or //18.08?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.gcc8#3]
Now that we have
* `org.freedesktop.Sdk/x86_64/1.6`,
* `org.freedesktop.Sdk/x86_64/18.08`,
* `org.freedesktop.Sdk.Extension.gcc8/x86_64/1.6`,
* `org.freedesktop.Sdk.Extension.openjdk10/x86_64/1.6` and such

It would be better if we had
* `org.freedesktop.Sdk.Extension.openjdk10/x86_64/18.08` because the aformentioned extension won't be usable after upgrading the base runtime of an application,
* `org.freedesktop.Sdk.Extension.clang6/x86_64/1.6` as the Clang version used in `org.freedesktop.Sdk/x86_64/18.08` is already the latest one,
* `org.freedesktop.Sdk.Extension.python3/x86_64/1.6` and probably `org.freedesktop.Platform.Extension.python3/x86_64/1.6`
* `org.freedesktop.Sdk.Extension.nodejs10/x86_64/1.6` and `org.freedesktop.Sdk.Extension.nodejs10/x86_64/18.08` but this might be unnecessary as there are already precompiled version of Node.js and managers like `nvm`

Thank you very much!

-----

Perhaps I need to mention @TingPing?

**Comment by TingPing** [comment]
I don't think it makes sense to bring a ton of things back o 1.6. We really want people to move to 18.08 if they need those things. (I realize GNOME/KDE based on it are not out yet but those are coming soon).

**Comment by amtlib-dot-dll** [comment]
You're right, but actually at least `org.freedesktop.Sdk.Extension.openjdk10/x86_64/18.08`, `org.freedesktop.Sdk.Extension.openjdk9/x86_64/18.08`, `org.freedesktop.Sdk.Extension.nodejs10/x86_64/18.08` and `org.freedesktop.Sdk.Extension.golang/x86_64/18.08` is missing. That's the point

**Comment by TingPing** [comment]
Yea, I think you should just open an issue against each of those. I think most of us will be busy this week but it should be easy to set up when we get a chance.

**Comment by barthalion** [comment]
18.08 already ships GCC 8.
