### ISSUE TITLE
Missing project license information from appdata file

### ISSUE THREAD

**Issue by mbooth101** [flathub/org.freedesktop.Sdk.Extension.gcc8#4]
This extension has no **<project_license/>** element in its ***.appdata.xml** file.

Please consider adding this information.

**Comment by barthalion** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.gcc8/commit/178a1db22e00ad3943066ff139998deb4db0e71c and https://github.com/flathub/org.freedesktop.Sdk.Extension.gcc8/commit/fa0355fcdd028b53b9b7558b2d51ec5581be665b
