### ISSUE TITLE
Newer GCC version

### ISSUE THREAD

**Issue by marbub** [flathub/org.freedesktop.Sdk.Extension.gcc8#8]
I am working on an IDE flatpak. It would be quite handy to provide newer GCC versions as extension, like the llvm extension is providing.

Is there a possibility to resurrect the GCC extension?

**Comment by hfiguiere** [comment]
The only way to solve that problem to submit a new package and maintnaining it.

This one is for gcc8 and long EOL.

**Comment by marbub** [comment]
Yes. I only wanted to ask, if there is a chance. Having the decision, after the work is done, is not very motivating. 😉
